slides:
  - Title
  - Intro
  - ThisTalk
  - Setup
  - SequentialBuild
  - PicardBuild
  - Fulfillment
  - MainResult
  - ProofLemma
  - Proof
  - GeneralPolicies
  - ExperimentalSetup
  - UniformDemand
  - HeavyTailedDemand
  - PolicyOpt
  - Mujoco
  - Mujoco2
  - Conclusion
